import type { LoaderFunctionArgs } from '@remix-run/node';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';

import { loader } from '../../app/routes/auth.callback.js';

import { assertRead, createTestMerchant, getTestClient, resetDb } from './setup.js';
import {
  buildOauthCallbackRequest,
  signOauthCallback,
} from './sign-oauth.js';
import {
  mockSubscribeFailure,
  mockTokenExchangeFailure,
  setupShopifyMocks,
} from './shopify-mock.js';

const SECRET = process.env.SHOPIFY_API_SECRET;
if (SECRET === undefined || SECRET.length === 0) {
  throw new Error(
    'SHOPIFY_API_SECRET not set — run via `pnpm web:test`, not bare vitest.',
  );
}
const SHOP = 'winback-test.myshopify.com';
const CODE = 'test_oauth_code_value';

async function invokeCallback(request: Request): Promise<Response> {
  const args: LoaderFunctionArgs = { request, params: {}, context: {} };
  try {
    return (await loader(args)) as Response;
  } catch (thrown) {
    if (thrown instanceof Response) return thrown;
    throw thrown;
  }
}

describe('/auth/callback OAuth completer (integration)', () => {
  setupShopifyMocks();

  beforeEach(async () => {
    await resetDb();
  });

  afterAll(async () => {
    await getTestClient().$disconnect();
  });

  it('happy path (new install) → 302 to / + Merchant + Session + Settings rows created', async () => {
    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(302);
    expect(res.headers.get('location')).toMatch(
      new RegExp(`^https://test\\.invalid/\\?shop=${SHOP.replace(/\./g, '\\.')}`),
    );
    // CSRF cookie should be cleared post-install.
    expect(res.headers.get('set-cookie')).toContain('winback_auth_state=;');

    const client = getTestClient();
    const merchants = await assertRead(() =>
      client.merchant.findMany({ where: { shop: SHOP } }),
    );
    expect(merchants).toHaveLength(1);
    expect(merchants[0]?.installedAt).toBeInstanceOf(Date);

    const settings = await assertRead(() =>
      client.merchantSettings.findMany({ where: { merchantId: merchants[0]!.id } }),
    );
    expect(settings).toHaveLength(1);

    const sessions = await assertRead(() =>
      client.session.findMany({ where: { shop: SHOP } }),
    );
    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.id).toBe(`offline_${SHOP}`);
    // Access token is encrypted at rest — should NOT equal the plaintext.
    expect(sessions[0]?.accessToken).not.toBe('shpat_test_token_for_harness');
    expect(sessions[0]?.accessToken.startsWith('v1:')).toBe(true);
  });

  it('reinstall for existing merchant → upserts (no duplicate Merchant row)', async () => {
    // Pre-existing merchant from a prior install.
    const existingId = await createTestMerchant(SHOP);

    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(302);

    const client = getTestClient();
    const merchants = await assertRead(() =>
      client.merchant.findMany({ where: { shop: SHOP } }),
    );
    expect(merchants).toHaveLength(1);
    expect(merchants[0]?.id).toBe(existingId);
    // uninstalledAt cleared on reinstall (if it had been set).
    expect(merchants[0]?.uninstalledAt).toBeNull();
  });

  it('missing state query param → 302 to /auth (restart flow)', async () => {
    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
      omitState: true,
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(302);
    expect(res.headers.get('location')).toBe(
      `/auth?shop=${encodeURIComponent(SHOP)}`,
    );
    expect(res.headers.get('set-cookie')).toContain('winback_auth_state=;');

    const client = getTestClient();
    const merchants = await assertRead(() => client.merchant.count());
    expect(merchants).toBe(0);
  });

  it('state mismatch (wrong state value) → 302 to /auth (restart flow)', async () => {
    // Build a request whose query `state` differs from the cookie's state.
    // The cookie's state is generated by generateState; we override the
    // query param to a different value, then re-sign with the right HMAC
    // (HMAC verification passes, state verification fails).
    const { request: legitRequest } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
      stateOverride: 'totally_different_state_value',
    });

    const res = await invokeCallback(legitRequest);

    expect(res.status).toBe(302);
    expect(res.headers.get('location')).toBe(
      `/auth?shop=${encodeURIComponent(SHOP)}`,
    );

    const client = getTestClient();
    expect(await assertRead(() => client.merchant.count())).toBe(0);
  });

  it('invalid HMAC → 401', async () => {
    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
      hmacOverride: 'deadbeef'.repeat(8), // 64 hex chars, wrong signature
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(401);

    const client = getTestClient();
    expect(await assertRead(() => client.merchant.count())).toBe(0);
  });

  it('token exchange fails (Shopify 401) → 302 to /auth (restart, no install)', async () => {
    mockTokenExchangeFailure();

    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(302);
    expect(res.headers.get('location')).toBe(
      `/auth?shop=${encodeURIComponent(SHOP)}`,
    );

    const client = getTestClient();
    expect(await assertRead(() => client.merchant.count())).toBe(0);
    expect(await assertRead(() => client.session.count())).toBe(0);
  });

  it('subscribeAllWebhooks fails (userErrors) → 302 to /auth (restart, no partial UI)', async () => {
    mockSubscribeFailure();

    const { request } = buildOauthCallbackRequest({
      shop: SHOP,
      code: CODE,
      secret: SECRET,
    });

    const res = await invokeCallback(request);

    expect(res.status).toBe(302);
    expect(res.headers.get('location')).toBe(
      `/auth?shop=${encodeURIComponent(SHOP)}`,
    );

    // Merchant + Session may exist (the route runs them BEFORE subscribe).
    // The contract is "no PARTIAL UI" — the merchant gets bounced back
    // through /auth so they don't land on a non-functional embedded app.
    // What we assert here is the response shape; cleanup of partially-
    // installed merchants is M10's job per handoff.
  });

  it('invalid shop domain → 400', async () => {
    // Cannot use buildOauthCallbackRequest because it asserts shop format
    // upstream. Hand-build a request with a clearly-invalid shop.
    const url = new URL('https://test.invalid/auth/callback');
    url.searchParams.set('shop', 'not a real shop');
    url.searchParams.set('code', CODE);
    url.searchParams.set('state', 'whatever');
    url.searchParams.set(
      'hmac',
      signOauthCallback(
        {
          shop: 'not a real shop',
          code: CODE,
          state: 'whatever',
        },
        SECRET,
      ),
    );
    const req = new Request(url.toString(), { method: 'GET' });

    const res = await invokeCallback(req);

    expect(res.status).toBe(400);
  });
});
